name: flutter_assignment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_rating_stars: ^1.0.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  logger: ^2.0.2+1
  page_transition: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_flavorizr: null
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  path: any

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/gemstore.jpg
  android: true

# flutter_native_splash:
#   image: "assets/images/gemstore.jpg"
#   color: "#FFFFFF"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
